apiVersion: v1
kind: Service
metadata:
  name: laravel-app
  labels:
    app: mysql
    tier: backend
    env: dev
spec:
  selector:
    app: mysql
    tier: backend
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
